"""Version identifier for the locale prompt files, for the translation-memory key.

The locale prompt (``prompts/locales/<lang>.md``) carries the register and
format rules for that language. It is therefore part of what produced a stored
translation, and leaving it out of ``tm_key`` means an edit to the prompt cannot
change the output: the cache answers first and the run reports success having
regenerated byte-identical copy.

That is not a hypothetical. ``de.md``, ``es.md`` and ``it.md`` each demanded a formal
form of address that the client's per-language rules (§7.1/§7.3/§7.5) forbid.
Correcting them without this term would have shipped the identical text and
logged a green run.
"""

from __future__ import annotations

import hashlib
from functools import lru_cache
from pathlib import Path

_LOCALES = Path(__file__).resolve().parent / "prompts" / "locales"


@lru_cache(maxsize=32)
def prompt_version(locale: str) -> str:
    """Short content hash of the locale prompt, or "" when there is no file.

    Returning "" for a missing file keeps behaviour identical to the pre-fix
    key, so a locale without a prompt file is not silently invalidated.
    """
    f = _LOCALES / f"{locale}.md"
    if not f.is_file():
        return ""
    return hashlib.sha256(f.read_bytes()).hexdigest()[:12]
