#!/usr/bin/env python3
"""Keep ONE GitHub issue in step with the Weglot exclusions that still need a manual import.

weglot-daily-report.yml used to run `gh issue create` on every day data/weglot.csv existed and
never closed anything. The exclusion sync that confirmed an import and cleared the CSV was
disabled on 2026-04-22 with two rows still pending; both were imported by hand, but nothing
could ever mark them done, so the report filed a new dated issue every day: 172 open, 0 closed
by 2026-10-06.

Now:
  * rows that Weglot already excludes are dropped (read-only public key) — "imported" no longer
    depends on a sync that may be switched off;
  * pending rows -> the issue is created once, edited when the rows change, never duplicated;
  * nothing pending -> the issue is closed.

Only an open issue whose title is EXACTLY TITLE and that carries LABEL is ever touched, so the
legacy dated issues are never edited or closed by this job.

CI usage:  GH_TOKEN=... GITHUB_REPOSITORY=owner/repo [WEGLOT_PUBLIC_KEY=...] \\
           python3 tools/weglot/pending_report.py
"""
from __future__ import annotations

import csv
import json
import os
import subprocess
import sys
import urllib.parse
import urllib.request
from pathlib import Path

TITLE = "Weglot: exclusions pending import"
LABEL = "weglot"
CSV_PATH = Path("data/weglot.csv")
SETTINGS_URL = "https://api.weglot.com/projects/settings"
USER_AGENT = "cel-weglot-pending-report/1.0"


def pending_rows(path: Path) -> list[tuple[str, str]]:
    """(url path, excluded languages) per data row. A missing or header-only file is nothing pending."""
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as fh:
        return [
            ((r.get("value") or "").strip(), (r.get("languages") or "").strip())
            for r in csv.DictReader(fh, delimiter=";")
            if (r.get("value") or "").strip()
        ]


def weglot_exclusion_paths(api_key: str) -> set[str] | None:
    """Paths Weglot already excludes exactly. None when they cannot be read, so the caller keeps
    every row instead of silently dropping one."""
    url = f"{SETTINGS_URL}?api_key={urllib.parse.quote(api_key)}"
    try:
        req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.load(resp)
        return {e["value"] for e in data.get("excluded_paths", []) if e.get("type") == "IS_EXACTLY" and e.get("value")}
    except (OSError, ValueError, KeyError) as exc:
        print(f"WARN: could not read Weglot exclusions ({exc}); reporting every CSV row", file=sys.stderr)
        return None


def build_body(rows: list[tuple[str, str]], repo: str) -> str:
    table = "\n".join(f"| {url} | {langs} |" for url, langs in rows)
    return (
        "## Weglot Exclusion Import Needed\n\n"
        f"**{len(rows)} blog post(s)** need translation exclusions in Weglot.\n\n"
        "### How to import\n"
        f"1. Download CSV: [weglot.csv](https://raw.githubusercontent.com/{repo}/main/data/weglot.csv)\n"
        "2. Go to [Weglot Translation Exclusions]"
        "(https://dashboard.weglot.com/workspaces/w-6bc645f5ad/projects/cel/settings/exclusions)\n"
        "3. Click **Actions** → **Import** → Upload the CSV\n"
        "4. Done — this issue closes itself on the next daily check once Weglot has the rows\n\n"
        "### Posts to exclude\n\n"
        "| URL | Excluded Languages |\n|---|---|\n"
        f"{table}\n\n"
        "---\n*Auto-generated by Weglot Daily Report — one issue, updated in place.*\n"
    )


def _norm(text: str) -> str:
    return text.replace("\r\n", "\n").strip()


def reconcile(rows: list[tuple[str, str]], repo: str, gh) -> str:
    """Bring the single tracking issue in line with `rows`. Returns what was done:
    created | updated | unchanged | closed | none."""
    issues = json.loads(gh(["issue", "list", "--repo", repo, "--label", LABEL, "--state", "open",
                            "--limit", "200", "--json", "number,title,body"]))
    mine = [i for i in issues if i["title"] == TITLE]
    if not rows:
        for issue in mine:
            gh(["issue", "close", str(issue["number"]), "--repo", repo, "--comment",
                "Nothing is pending any more: Weglot has every exclusion, so this issue closes itself."])
        return "closed" if mine else "none"
    body = build_body(rows, repo)
    if not mine:
        gh(["issue", "create", "--repo", repo, "--title", TITLE, "--label", LABEL, "--body", body])
        return "created"
    if _norm(mine[0].get("body") or "") == _norm(body):
        return "unchanged"
    gh(["issue", "edit", str(mine[0]["number"]), "--repo", repo, "--body", body])
    return "updated"


def _gh(args: list[str]) -> str:
    done = subprocess.run(["gh", *args], capture_output=True, text=True, check=False)
    if done.returncode != 0:
        raise RuntimeError(f"gh {' '.join(args[:2])} failed ({done.returncode}): {done.stderr.strip()[:300]}")
    return done.stdout


def main() -> int:
    repo = os.environ.get("GITHUB_REPOSITORY", "")
    if not repo:
        print("GITHUB_REPOSITORY is not set", file=sys.stderr)
        return 2
    rows = pending_rows(CSV_PATH)
    key = os.environ.get("WEGLOT_PUBLIC_KEY", "")
    if rows and key:
        present = weglot_exclusion_paths(key)
        if present is not None:
            imported = [url for url, _ in rows if url in present]
            if imported:
                print(f"{len(imported)} CSV row(s) are already in Weglot (nothing to import): {', '.join(imported)}")
            rows = [r for r in rows if r[0] not in present]
    print(f"pending imports: {len(rows)}")
    print(f"issue: {reconcile(rows, repo, _gh)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
