import sys
import os
import json
import pathlib
import requests
import logging
from lxml import etree
from urllib.parse import urlparse
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

PRIMARY_SITEMAP = "https://www.englishcollege.com/sitemap.xml"
REGIONAL_SITEMAPS = [
    "https://www.englishcollege.com/es/sitemap.xml",
    "https://www.englishcollege.com/de/sitemap.xml",
    "https://www.englishcollege.com/fr/sitemap.xml",
    "https://www.englishcollege.com/ko/sitemap.xml",
    "https://www.englishcollege.com/pt/sitemap.xml",
    "https://www.englishcollege.com/it/sitemap.xml",
    "https://www.englishcollege.com/ja/sitemap.xml",
    "https://www.englishcollege.com/ar/sitemap.xml"
]

# Category path segments across all languages — these pages are noindex
# and must be excluded from the sitemap to avoid conflicting signals.
CATEGORY_SEGMENTS = ["/category/", "/kategorie/", "/categorie/", "/categoria/"]

# Weglot exclusion data — maps post paths to excluded language codes.
# Generated by tools/weglot/sync_exclusions.py
EXCLUSION_DATA_FILE = os.path.join(os.path.dirname(__file__), "..", "data", "weglot-sitemap-exclusions.json")

# Language code → URL prefix mapping
LANG_PREFIXES = {
    "es": "/es/", "de": "/de/", "fr": "/fr/", "ko": "/ko/",
    "pt": "/pt/", "it": "/it/", "ja": "/ja/", "ar": "/ar/",
}

# Webflow blog collection + its `language` reference-field item IDs.
# A post's native language decides its canonical sitemap URL: English posts
# live at /post/<slug>; every other language lives at /<lang>/post/<slug>.
# Weglot's regional sitemaps are unreliable (they omit some live locale pages),
# so the CMS `language` field — not the regional sitemap — is the source of
# truth for a post's locale. Keep in sync with tools/weglot/api_sync.py.
BLOG_COLLECTION_ID = "667453c576e8d35c454ccaae"
LANGUAGE_ID_MAP = {
    "6876590744e1f69b128ef245": "en",
    "6876596a3a4d6e078bebe528": "de",
    "687659b3281d98a9803a86ae": "fr",
    "6876591fab42b61d6b9f6a96": "es",
    "6876597d1d2fe4f1a294fd77": "ko",
    "687659cca45f80dbea92430c": "it",
    "6876599de124298a6bd8cb8d": "pt",
    "687659e4ab42b61d6b9f6a96": "ja",
    "687659fe11c147ceed4f09cd": "ar",
}

# Logging is configured in _setup_logging(), invoked from main() — NOT at import
# time — so importing this module (e.g. from tests) has no filesystem side effects
# (rules/quality.md §12: module-level code must be side-effect-free).
_logging_configured = False

def _setup_logging():
    """Configure console + persistent run_log.txt logging. Idempotent."""
    global _logging_configured
    if _logging_configured:
        return
    log_formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
    root_logger = logging.getLogger()
    root_logger.setLevel(logging.INFO)

    # Console output
    console_handler = logging.StreamHandler()
    console_handler.setFormatter(log_formatter)
    root_logger.addHandler(console_handler)

    # File output (append mode, truncated below if it grows past 1MB)
    file_handler = logging.FileHandler('run_log.txt', mode='a')
    file_handler.setFormatter(log_formatter)
    root_logger.addHandler(file_handler)

    # Keep log file size reasonable (truncate if > 1MB)
    try:
        if os.path.getsize('run_log.txt') > 1024 * 1024:
            with open('run_log.txt', 'w') as f:
                f.write("--- Log Rotated ---\n")
    except FileNotFoundError:
        pass

    _logging_configured = True

def load_weglot_exclusions():
    """Load the Weglot exclusion map: { "/post/slug": ["ar","de",...], ... }"""
    try:
        with open(EXCLUSION_DATA_FILE) as f:
            data = json.load(f)
            logging.info(f"Loaded Weglot exclusion data: {len(data)} post exclusion rules")
            return data
    except FileNotFoundError:
        logging.info("No Weglot exclusion data found — skipping language-aware filtering")
        return {}
    except json.JSONDecodeError as e:
        logging.warning(f"Weglot exclusion data is invalid JSON: {e}")
        return {}

def is_excluded_translation(url, exclusion_map):
    """Check if a regional URL is an excluded translation that should be removed.

    For example, if /post/my-slug excludes ["de","fr"] then:
    - https://www.englishcollege.com/de/post/my-slug → True (remove)
    - https://www.englishcollege.com/fr/post/my-slug → True (remove)
    - https://www.englishcollege.com/es/post/my-slug → False (keep)
    """
    if not exclusion_map:
        return False
    path = urlparse(url).path
    if '/post/' not in path:
        return False
    for lang_code, prefix in LANG_PREFIXES.items():
        if path.startswith(prefix) and '/post/' in path:
            # Extract the post path without the language prefix
            post_path = path[len(prefix) - 1:]  # e.g. /de/post/slug → /post/slug
            excluded_langs = exclusion_map.get(post_path, [])
            if lang_code in excluded_langs:
                return True
    return False

def create_robust_session():
    """Create a requests session with automatic retries for transient network errors"""
    session = requests.Session()
    # Retry 3 times with exponential backoff on common server/network errors
    retry = Retry(
        total=3,
        backoff_factor=1,
        status_forcelist=[429, 500, 502, 503, 504]
    )
    adapter = HTTPAdapter(max_retries=retry)
    session.mount("http://", adapter)
    session.mount("https://", adapter)
    return session

def fetch_sitemap_urls(session, url):
    logging.info(f"Fetching {url}... ")
    try:
        response = session.get(url, timeout=15)
        response.raise_for_status()
        # Fresh hardened parser per call — disable external entity resolution and
        # network access (defense-in-depth), and avoid sharing mutable parser
        # state across fetches (a malformed sitemap mustn't affect later parses).
        parser = etree.XMLParser(resolve_entities=False, no_network=True)
        root = etree.fromstring(response.content, parser)
        
        # Find all <url> elements to preserve metadata (lastmod, changefreq, images, etc.)
        nsmap = {'ns': 'http://www.sitemaps.org/schemas/sitemap/0.9'}
        url_elements = root.xpath('//ns:url', namespaces=nsmap)
        if not url_elements:
            url_elements = root.xpath('//url')
            
        results = []
        for el in url_elements:
            loc_el = el.find('ns:loc', namespaces=nsmap)
            if loc_el is None:
                loc_el = el.find('loc')
                
            if loc_el is not None and loc_el.text:
                results.append({"url": loc_el.text.strip(), "element": el})
                
        logging.info(f"  -> Successfully found {len(results)} URLs in {url}.")
        return results
    except requests.exceptions.RequestException as e:
        logging.error(f"  -> Network error fetching {url} after 3 retries: {e}")
        return []
    except etree.XMLSyntaxError as e:
        logging.error(f"  -> XML Parsing error for {url}: {e}")
        return []
    except Exception as e:
        logging.error(f"  -> Unexpected error fetching {url}: {e}")
        return []

def is_category_url(url):
    """Check if a URL is a noindex category page (any language variant)."""
    path = urlparse(url).path
    return any(seg in path for seg in CATEGORY_SEGMENTS)

def get_slug_from_post_url(url):
    """
    Extracts the slug from a URL containing '/post/'.
    e.g. 'https://www.englishcollege.com/fr/post/san-diego' -> 'san-diego'
    """
    if '/post/' in url:
        parts = url.split('/post/')
        if len(parts) > 1:
            slug_part = parts[-1].strip('/')
            return slug_part.split('/')[0] # Get the immediate segment after /post/
    return None

def post_url_for(lang_code, slug):
    """Canonical sitemap URL for a blog post given its native language code.

    English posts live at the root (/post/<slug>); every other language lives
    under its locale prefix (/<lang>/post/<slug>). This mirrors how Weglot
    serves the pages and what each post's per-item canonical tag points at.
    """
    if not lang_code or lang_code == "en":
        return f"https://www.englishcollege.com/post/{slug}"
    return f"https://www.englishcollege.com/{lang_code}/post/{slug}"

def fetch_cms_posts(session, token):
    """Fetch all blog CMS items (paginated). Returns [] on any failure so the
    pipeline degrades to regional-sitemap-only dedup rather than crashing."""
    if not token:
        return []
    headers = {"Authorization": f"Bearer {token}", "accept": "application/json"}
    url = f"https://api.webflow.com/v2/collections/{BLOG_COLLECTION_ID}/items"
    posts = []
    offset = 0
    while True:
        try:
            resp = session.get(url, headers=headers, params={"limit": 100, "offset": offset}, timeout=30)
        except requests.exceptions.RequestException as e:
            logging.warning(f"CMS API request failed ({e}); CMS-aware locale logic disabled this run.")
            return []
        if resp.status_code != 200:
            logging.warning(f"CMS API returned {resp.status_code}; CMS-aware locale logic disabled this run.")
            return []
        data = resp.json()
        posts.extend(data.get("items", []))
        total = data.get("pagination", {}).get("total", len(posts))
        if len(posts) >= total:
            break
        offset += 100
    return posts

def build_post_lang_map(cms_posts):
    """Map slug -> native language code for every published, non-archived post.

    Unmapped language reference IDs default to English (the Webflow root URL),
    which is the safe fallback if a new locale is added to the CMS before this
    script's LANGUAGE_ID_MAP is updated.
    """
    lang_by_slug = {}
    for item in cms_posts:
        if item.get("isArchived"):
            continue
        if not item.get("lastPublished"):
            continue
        fd = item.get("fieldData", {})
        slug = fd.get("slug", "")
        if not slug:
            continue
        lang_id = fd.get("language")
        if not lang_id:
            logging.warning(f"/post/{slug} has no language field — defaulting to English root URL.")
        elif lang_id not in LANGUAGE_ID_MAP:
            logging.warning(f"Unknown language id {lang_id!r} for /post/{slug} — defaulting to English root URL.")
        lang_by_slug[slug] = LANGUAGE_ID_MAP.get(lang_id, "en")
    return lang_by_slug

def main():
    _setup_logging()
    logging.info("========== STEP 1: Process Regional Sitemaps ==========")
    regional_urls = []
    regional_slugs = set()
    session = create_robust_session()
    exclusion_map = load_weglot_exclusions()
    excluded_translation_count = 0

    for sitemap_url in REGIONAL_SITEMAPS:
        data = fetch_sitemap_urls(session, sitemap_url)
        for item in data:
            if is_category_url(item["url"]):
                continue  # Skip noindex category pages
            if is_excluded_translation(item["url"], exclusion_map):
                excluded_translation_count += 1
                continue  # Skip excluded translations (Weglot)
            regional_urls.append(item)
            slug = get_slug_from_post_url(item["url"])
            if slug:
                regional_slugs.add(slug)

    if excluded_translation_count:
        logging.info(f"\nRemoved {excluded_translation_count} Weglot-excluded translated post URLs from regional sitemaps.")
    logging.info(f"\nTotal Regional URLs: {len(regional_urls)}")
    logging.info(f"Total Unique Regional Slugs from '/post/': {len(regional_slugs)}")

    # Fetch CMS posts once. Used by STEP 2 (drop English-root phantoms of
    # natively-foreign posts) and STEP 2.5 (inject missing posts at the correct
    # locale). Gated on WEBFLOW_API_TOKEN; without it post_lang_by_slug is empty
    # and the script falls back to regional-sitemap-only dedup.
    webflow_token = os.environ.get("WEBFLOW_API_TOKEN", "").strip()
    cms_posts = fetch_cms_posts(session, webflow_token)
    post_lang_by_slug = build_post_lang_map(cms_posts)
    if post_lang_by_slug:
        logging.info(f"Loaded native language for {len(post_lang_by_slug)} published CMS posts.")

    logging.info("\n========== STEP 2: Process Primary Sitemap ==========")
    primary_urls = fetch_sitemap_urls(session, PRIMARY_SITEMAP)
    logging.info(f"Total Primary URLs Before Filtering: {len(primary_urls)}")

    if len(primary_urls) == 0:
        logging.error("CRITICAL FAILURE: Could not fetch the Primary Sitemap or it was empty. Aborting to prevent overriding the live sitemap with an empty file.")
        sys.exit(1)

    # Check for Weglot-injected translated URLs in primary (these duplicate regional sitemaps)
    lang_prefixes = ["/es/", "/de/", "/fr/", "/ko/", "/pt/", "/it/", "/ja/", "/ar/"]
    translated_in_primary = [item for item in primary_urls
                             if any(urlparse(item["url"]).path.startswith(p) for p in lang_prefixes)]
    if translated_in_primary:
        logging.warning(f"Primary sitemap contains {len(translated_in_primary)} translated (non-English) URLs — these will duplicate regional sitemaps.")
        for item in translated_in_primary[:5]:
            logging.warning(f"  Example: {item['url']}")
    else:
        logging.info("Primary sitemap contains only English URLs (no Weglot injection — good).")
    
    cleaned_primary_urls = []
    removed_urls = []
    removed_foreign_root = []
    removed_category_count = 0
    for item in primary_urls:
        u = item["url"]
        if is_category_url(u):
            removed_category_count += 1
            continue  # Skip noindex category pages
        if '/post/' in u:
            slug = get_slug_from_post_url(u)
            is_en_root = urlparse(u).path.startswith('/post/')
            native = post_lang_by_slug.get(slug)
            if is_en_root and native and native != "en":
                # Natively-foreign post: its English-root URL is a phantom whose
                # canonical lives at /<lang>/post/<slug>. Drop it here regardless
                # of whether the (unreliable) regional sitemap lists the locale
                # version — STEP 2.5 injects the correct URL if it's missing.
                removed_foreign_root.append((native, slug))
                continue
            if slug and slug in regional_slugs:
                removed_urls.append((slug, u))
                continue  # Regional version is the canonical — remove root duplicate
        cleaned_primary_urls.append(item)

    if removed_category_count:
        logging.info(f"\nRemoved {removed_category_count} noindex category URLs from primary sitemap.")
    if removed_foreign_root:
        logging.info(f"Removed {len(removed_foreign_root)} English-root phantoms of non-English posts (CMS language):")
        for native, slug in sorted(removed_foreign_root):
            logging.info(f"  - /post/{slug}  → canonical is /{native}/post/{slug}")
    logging.info(f"\nRemoved {len(removed_urls)} duplicate English '/post/' URLs.")
    if removed_urls:
        logging.info("Removed English phantom URLs (slug → regional version exists):")
        for slug, url in sorted(removed_urls):
            logging.info(f"  - /post/{slug}  ({url})")
    logging.info(f"Total Primary URLs After Filtering: {len(cleaned_primary_urls)}")

    logging.info("\n========== STEP 2.5: Inject Missing Published Posts from CMS ==========")
    injected_count = 0
    if cms_posts:
        existing_post_slugs = set()
        for item in cleaned_primary_urls + regional_urls:
            slug = get_slug_from_post_url(item["url"])
            if slug:
                existing_post_slugs.add(slug)

        for item in cms_posts:
            if item.get("isArchived", False):
                continue
            if not item.get("lastPublished"):
                continue
            fd = item.get("fieldData", {})
            slug = fd.get("slug", "")
            if not slug or slug in existing_post_slugs:
                continue

            # Published but missing from every sitemap — inject it at its correct
            # locale (English at the root, every other language locale-prefixed).
            native = post_lang_by_slug.get(slug, "en")
            loc_url = post_url_for(native, slug)
            url_el = etree.Element("url")
            loc_el = etree.SubElement(url_el, "loc")
            loc_el.text = loc_url
            lastmod_el = etree.SubElement(url_el, "lastmod")
            lastmod_el.text = item["lastPublished"][:10]  # YYYY-MM-DD
            cleaned_primary_urls.append({"url": loc_url, "element": url_el})
            existing_post_slugs.add(slug)
            injected_count += 1
            logging.info(f"  Injected: {loc_url}")

        logging.info(f"Injected {injected_count} missing published posts from CMS")
    elif not webflow_token:
        logging.info("WEBFLOW_API_TOKEN not set — skipping CMS injection")
    else:
        logging.info("No CMS posts available — skipping CMS injection")

    logging.info("\n========== STEP 3: Combine and Generate Master Sitemap ==========")
    all_final_urls = cleaned_primary_urls + regional_urls
    # Final safety dedup by loc URL — belt-and-suspenders against any overlap
    # between the cleaned primary set, the regional sets, and CMS injections.
    seen_urls = set()
    deduped = []
    for item in all_final_urls:
        if item["url"] in seen_urls:
            continue
        seen_urls.add(item["url"])
        deduped.append(item)
    if len(deduped) != len(all_final_urls):
        logging.info(f"Final dedup removed {len(all_final_urls) - len(deduped)} duplicate URL(s).")
    all_final_urls = deduped
    logging.info(f"Total Combined URLs for Master Sitemap: {len(all_final_urls)}")
    
    if len(all_final_urls) == 0:
        logging.error("CRITICAL FAILURE: Generating a sitemap with 0 URLs. Aborting.")
        sys.exit(1)
    
    # Create the root element, collecting custom namespaces if possible
    # A standard sitemap usually has the xml namespace, but xhtml and image are common too.
    nsmap = {
        None: "http://www.sitemaps.org/schemas/sitemap/0.9",
        "xhtml": "http://www.w3.org/1999/xhtml",
        "image": "http://www.google.com/schemas/sitemap-image/1.1"
    }
    urlset = etree.Element("urlset", nsmap=nsmap)
    
    for item in all_final_urls:
        # Deepcopy the original element to avoid moving it between documents weirdly
        new_el = etree.SubElement(urlset, "url")
        # Copy children of original element to new element
        for child in item["element"]:
            new_el.append(etree.fromstring(etree.tostring(child)))
        
    tree = etree.ElementTree(urlset)
    # Public web files live under docs/ (GH Pages serves main:/docs).
    master_file = "docs/sitemap.xml"
    pathlib.Path(master_file).parent.mkdir(parents=True, exist_ok=True)

    # Write to file with pretty formatting and xml declaration
    tree.write(master_file, pretty_print=True, xml_declaration=True, encoding="utf-8")
    logging.info(f"\nSuccess! Standard XML Sitemap generated at '{master_file}'.")

if __name__ == "__main__":
    main()
